### ISSUE TITLE
Произвести выбор библиотеки, используемой для логов программы.

### ISSUE THREAD

**Issue by SozonovAA** [SozonovAA/ISP#9]
Предложение к рассмотрению: 
boost::log
log4cxx

**Comment by DubovtsevNK** [comment]
https://habr.com/ru/post/313686/

**Comment by SozonovAA** [comment]
@DubovtsevNK 
В соответствии со статьей предлагаю начнем использовать http://baical.net/p7.html 
Если возникнут трудности, пересмотрим данное решение.
